from . import base_archive
from . import hostel
from . import hostel_room
from . import hostel_student
from . import hostel_amenities
from . import hostel_category
from . import hostel_room_copy
from . import hostel_book
from . import hostel_room_member
from ..wizard import assign_room_student_wizard